spring:
  config:
    import:
      - classpath:/yml/common.yml
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  data:
    mongodb:
      uri: mongodb://localhost:27017/yourDatabaseName
      embedded:
        version: 4.4.2