spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${maria.host}:${maria.port}/${maria.dbname}?serverTimezone=Asia/Seoul
    username: ${maria.username}
    password: ${maria.password}

  data:
    mongodb:
      host: ${mongo.host}
      port: ${mongo.port}
      database: ${mongo.collection}